/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

@SuppressWarnings("java:S106")
public class HelloOtus5 {
    public static void main(String... args) {
        TestLoggingInterface myClass = LogAspect.createMyClass();
        myClass.calculation(1);
        myClass.calculation(2, 3);
        myClass.calculation(4, 5, "Цифра6");
        myClass.calculation(7, "Нет логгирования", "Нет логгирования");
        myClass.alsoCalculation(1);
        myClass.alsoCalculation(2, 3);
        myClass.alsoCalculation(4, 5, "Цифра6");
        myClass.alsoCalculation(7, "Нет логгирования", "Нет логгирования");
    }
}
