/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import java.util.HashMap;

@SuppressWarnings("java:S106")
public class HelloOtus {
    public static void main(String... args) {
        Atm atm = new Atm();
        HashMap<Denomination, Integer> money = new HashMap<>();
        money.put(Denomination.RUB100, 1);
        money.put(Denomination.RUB500, 3);
        atm.add(money);
        atm.dispense(1100);
        atm.printBalance();
    }
}
